### ISSUE TITLE
Update logos

### ISSUE THREAD

**Issue by costateixeira** [IHE/ihe-ig-template#1]
Add logo with Registered mark and transparent background

**Comment by JohnMoehrke** [comment]
Attached are two that I use. There is a Marketing directory on the ftp site at ftp://ftp.ihe.net/MarketingAndPresentations/.

 

IHE International logo at ftp://ftp.ihe.net/MarketingAndPresentations/branding_materials/IHE%20International%20Logo/.

 

IHE Regional and Domain logos at ftp://ftp.ihe.net/MarketingAndPresentations/branding_materials/IHE_Brand_Materials_2013/.

 

Logo with no text at ftp://ftp.ihe.net/MarketingAndPresentations/branding_materials/IHE_Brand_Materials_2013/IHE%20Logo%20w_o%20text/.

 

Let me know if you need something else.

 

Thanks,

Mary

**Comment by JohnMoehrke** [comment]
Is it possible to use a image hosted on IHE web site? Or does the image need to be included within the template?

**Comment by costateixeira** [comment]
The image url can be anywhere.

1- Putting it in the template isolates us from unwanted changes at least
for now.
2- Linking to an existing one reduces duplication...

For now I'd prefer 1. We can change at any time

Kind regards

**Comment by JohnMoehrke** [comment]
Okay.

John Moehrke 🔥 Architect: Healthcare Informatics Standards -
Interoperability, Privacy, and Security
CyberPrivacy – Enabling authorized communications while respecting Privacy
IHE Co-Chair IT Infrastructure Planning
HL7 Co-Chair Security WG, FHIR FMG, FHIR facilitator, and FHIR Foundation
founding member
HITRUST Certified CSF Practitioner
Employee of ByLight Professional IT Services -- Contractor to VHA
MyHealtheVet
JohnMoehrke@gmail.com  |  M +1 920-564-2067  |  John.Moehrke@bylight.com
https://www.linkedin.com/in/johnmoehrke   |
https://healthcaresecprivacy.blogspot.com
Courtney's third law: There are no technical solutions to management
problems, but there are management solutions to technical problems.
