### ISSUE TITLE
Define the feedback mechanism for Profiles

### ISSUE THREAD

**Issue by costateixeira** [IHE/ihe-ig-template#7]
HL7 has Jira, so it is possible to have a link "provide feedback on this section". 
We currently have a link at the bottom that sends the reader to the CP process, presumably that could also be made leaner

**Comment by JohnMoehrke** [comment]
agreed. I don't expect jira to become an IHE tool any-time-soon. It might happen, but there are no discussions and no funding for that.

I think the only approved process is the CP process, the wiki page you mention.

For the IG that I am working on, the ITI committee has agreed to allow github issue tracking to be used. That is to say for that IG, the issue tracking on the github repo for that IG source. Is this possible to do from the template? is this something that could be overridden in the IG source?

**Comment by JohnMoehrke** [comment]
can the template support different mechanisms per each IG? With a default that we manage in the template?

**Comment by JohnMoehrke** [comment]
using input/data/features.yml function
